"""movie table

Revision ID: eb37195d49cb
Revises: 1ec9cf541cb5
Create Date: 2021-10-07 20:11:27.254396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb37195d49cb'
down_revision = '1ec9cf541cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('meister_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=4000), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('length_minute', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['meister_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_event_date'), 'movie', ['event_date'], unique=False)
    op.create_index(op.f('ix_movie_length_minute'), 'movie', ['length_minute'], unique=True)
    op.create_index(op.f('ix_movie_rating'), 'movie', ['rating'], unique=True)
    op.create_index(op.f('ix_movie_timestamp'), 'movie', ['timestamp'], unique=False)
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=True)
    op.create_index(op.f('ix_movie_year'), 'movie', ['year'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_year'), table_name='movie')
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_index(op.f('ix_movie_timestamp'), table_name='movie')
    op.drop_index(op.f('ix_movie_rating'), table_name='movie')
    op.drop_index(op.f('ix_movie_length_minute'), table_name='movie')
    op.drop_index(op.f('ix_movie_event_date'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
