"""init

Revision ID: fe0c0ca8f37a
Revises: 
Create Date: 2021-10-10 15:37:10.283446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0c0ca8f37a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('meister_id', sa.Integer(), nullable=True),
    sa.Column('imbd_code', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=4000), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('length_minute', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['input_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['meister_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_event_date'), 'movie', ['event_date'], unique=False)
    op.create_index(op.f('ix_movie_imbd_code'), 'movie', ['imbd_code'], unique=True)
    op.create_index(op.f('ix_movie_length_minute'), 'movie', ['length_minute'], unique=True)
    op.create_index(op.f('ix_movie_rating'), 'movie', ['rating'], unique=True)
    op.create_index(op.f('ix_movie_timestamp'), 'movie', ['timestamp'], unique=False)
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=True)
    op.create_index(op.f('ix_movie_year'), 'movie', ['year'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_year'), table_name='movie')
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_index(op.f('ix_movie_timestamp'), table_name='movie')
    op.drop_index(op.f('ix_movie_rating'), table_name='movie')
    op.drop_index(op.f('ix_movie_length_minute'), table_name='movie')
    op.drop_index(op.f('ix_movie_imbd_code'), table_name='movie')
    op.drop_index(op.f('ix_movie_event_date'), table_name='movie')
    op.drop_table('movie')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
